#python program to convert into resume from python forms, 

name = input("Enter your name:")
bio = input("Enter your bio:")
email = input("Enter your email:")
phone = input("Enter your phone number:")
address = input("Enter your address:")
headline = input("Enter your headline:")
photo= input("Enter your photo URL:")
resume_url = input("Enter your resume URL:")
education = input("Enter your education:")
skills = input("Enter your skills:")
experience = input("Enter your experience:")
print("Name:", name)
print("Bio:", bio)
print("Email:", email)
print("Phone:", phone)
print("Address:", address)
print("Headline:", headline)
print("Photo URL:", photo)
print("Resume URL:", resume_url)
print("Education:", education)
print("Skills:", skills)
print("Experience:", experience)